[build]
  command = "npm run build:all"
  publish = "dist"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/rider/*"
  to = "/rider/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
