FROM python:3.12-slim
WORKDIR /app
RUN apt-get update && apt-get install -y --no-install-recommends libpq-dev && rm -rf /var/lib/apt/lists/*
COPY requirements-django.txt .
RUN pip install --no-cache-dir -r requirements-django.txt
COPY django_app/ .
EXPOSE 8001
CMD ["python", "manage.py", "runserver", "0.0.0.0:8001"]
